### ISSUE TITLE
libboost_system.so.1.65.1

### ISSUE THREAD

**Issue by coolrip007** [GamepassNetwork/GamepassClassic#2]
the wallet linux ver. ubuntu 22.04 the wallet needs libboost_system.so.1.65.1!
But the linux wallet for XDA just works fine and all ubuntu vers! but i noticed gamepass and also Clore.ai are asking for libboost_system.so.1.65.1
  and i tried every thing! why it just just works!!!

**Comment by coolrip007** [comment]
so can u do like https://github.com/NeuraiProject/Neurai/releases/tag/1.0.2  they use kawpow algo wallet too but it just works with no issues! BUT not yours! and would like to be able to use this lunix wallet plz what commands to use??

**Comment by GamepassNetwork** [comment]
Hello, you can build the node for Ubuntu 22.04 using the following set of
commands:

sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install build-essential libdb++-dev libtool
autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
python3
sudo apt-get -y install libboost-system-dev libboost-filesystem-dev
libboost-chrono-dev libboost-program-options-dev libboost-test-dev
libboost-thread-dev
git clone https://github.com/GamepassNetwork/Gamepasscd Gamepasschmod
755 contrib/install_db4.sh && ./contrib/install_db4.sh ..chmod 755
autogen.sh && ./autogen.sh
./configure --disable-tests --disable-bench
BDB_LIBS="-L/home/user/db4/lib -ldb_cxx-4.8"
BDB_CFLAGS="-I/home/user/db4/include" --with-gui=nochmod 755
~/Gamepass/share/genbuild.sh
make
sudo make install

**Comment by GamepassNetwork** [comment]
Hello, you can build the node for Ubuntu 22.04 using the following set of commands:
`sudo apt-get -y update && sudo apt-get -y upgrade`
`sudo apt-get -y install build-essential libdb++-dev libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3`
`sudo apt-get -y install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev`
`git clone https://github.com/GamepassNetwork/Gamepass`
`cd Gamepass`
`chmod 755 contrib/install_db4.sh && ./contrib/install_db4.sh ..`
`chmod 755 autogen.sh && ./autogen.sh`
`./configure --disable-tests --disable-bench BDB_LIBS="-L/home/user/db4/lib -ldb_cxx-4.8" BDB_CFLAGS="-I/home/user/db4/include" --with-gui=no`
`chmod 755 ~/Gamepass/share/genbuild.sh`
`make`
`sudo make install`
